### ISSUE TITLE
Using group "docker" always is a problem if docker is not being used.

### ISSUE THREAD

**Issue by mmarquezs** [wych42/ansible-role-traefik#1]
Hi, 
Just an small issue I saw, here you define the user with the group 'docker'. This causes issues if docker is not installed & not planning on using docker because this step fails. A check for the existing variable **traefik_enable_docker_provider** value could be used to add docker or istead use traefik as a group. Or alternatively a new variable. 

https://github.com/wych42/ansible-role-traefik/blob/6d1dc81138bede3854c645b704f9a3e12e8225df/tasks/install.yml#L70-L73

**Comment by wych42** [comment]
Can you try this #2  out? I've tested it on my local machine, seems ok.

**Comment by mmarquezs** [comment]
Ok Thanks!, I will try to test it later in the week an the and report back.

**Comment by mmarquezs** [comment]
Sorry I was distracted with other things and since I already had a workaround I completely forgot.
I tested today redeploying my container and it worked fine with your PR.
